### ISSUE TITLE
主题下需要添加讲师个人介绍。

### ISSUE THREAD

**Issue by tao12345666333** [PyConChina/PyConChina2016#19]

**Comment by tao12345666333** [comment]
另外，还是希望能在日程页面http://cn.pycon.org/2016/shenzhen.html 的每个嘉宾名字后面有个简短介绍。

潘俊勇，易度云（easydo.cn）创始人

丁来强，Splunk

李力，腾讯云调度管理系统研发负责人

River，创业者，优趣工作室CTO,  QPython作者，前Zynga高级系统研发工程师，前绿盟科技研发工程师，前新浪邮件工程师

何世友，爱范儿 CTO

张其川，CheungSSH总设计师

胡国涛，优趣工作室 WEGO 项目组高级工程师

馋师，互联网公司后端开发

石恩名，广州优亿科技有限公司高级技术经理

汤英康，广州优亿科技Python程序员

**Comment by NsLib** [comment]
#
